
INCORRECT_DECORATOR_USE = -101
NO_DATABASE_CONNECTION = -1
NEW_CONNECTION = 1
OLD_CONNECTION = 0
OK = 1
URL_EXISTS = -2
DATA_NOT_FOUND = -4
INVALID_URL = -3

FLASH_CATEGORY = {
   OK: 'success',
   URL_EXISTS: 'info',
   NO_DATABASE_CONNECTION: 'danger',
   INVALID_URL: 'danger'
}
